version: "3.8"

services: 
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes: 
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    restart: always

  learning-state-service:
    build:
      context: .
      dockerfile: ./source_code/KnowledgeApp.LearningState/src/KnowledgeApp.LearningState.Service/Dockerfile
    container_name: learning-state-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017
      - REDIS_CONNECTION_STRING=redis:6379  # Connection string for Redis
    depends_on:
      - mongo
      - rabbitmq
      - redis  # Ensure Redis starts before the service

  paragraph-service:
    build:
      context: .
      dockerfile: ./source_code/KnowledgeApp.Paragraph/src/KnowledgeApp.Paragraph.Service/Dockerfile
    container_name: paragraph-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017
      - REDIS_CONNECTION_STRING=redis:6379  # Connection string for Redis
    depends_on:
      - mongo
      - rabbitmq
      - redis  # Ensure Redis starts before the service

  user-service:
    build:
      context: .
      dockerfile: ./source_code/KnowledgeApp.User/src/KnowledgeApp.User.Service/Dockerfile
    container_name: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017
      - REDIS_CONNECTION_STRING=redis:6379  # Connection string for Redis
    depends_on:
      - mongo
      - rabbitmq
      - redis  # Ensure Redis starts before the service

  api-gateway:
    build:
      context: .
      dockerfile: ./source_code/KnowledgeApp.ApiGateway/src/KnowledgeApp.ApiGateway/Dockerfile
    container_name: api-gateway-service
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - learning-state-service
      - paragraph-service
      - user-service

volumes: 
  mongodbdata:
  rabbitmqdata:
  redisdata:  # Volume for Redis data
